# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn

    - name: Setup VPN
      run: |
        echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
        sudo openvpn --config vpn-config.ovpn --daemon
        sleep 20
        sudo pkill -f openvpn
        sudo openvpn --config vpn-config.ovpn --daemon
      env:
        VPN_CONFIG: ${{ secrets.VPN_CONFIG }}

    - name: Wait for VPN connection
      run: sleep 20

    - name: Verify VPN connection
      run: |
        ip a
        sudo journalctl -u openvpn

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 10.17.10.4 >> ~/.ssh/known_hosts
        sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -r ./tp_api alt@10.17.10.4:/home/alt/tp_api/
